basePath: /random
info:
  contact: {}
  description: API для анонимного чата с использованием WebSocket.
  title: Random-Chat API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - text/html
      description: Отображает домашнюю страницу приложения.
      produces:
      - text/html
      responses:
        "200":
          description: HTML страницы успешно загружен
          schema:
            type: string
      summary: Home Page
      tags:
      - Pages
  /chat:
    get:
      consumes:
      - text/html
      description: Отображает страницу чата приложения.
      produces:
      - text/html
      responses:
        "200":
          description: HTML страницы успешно загружен
          schema:
            type: string
      summary: Chat Page
      tags:
      - Pages
  /ws:
    get:
      description: Создает WebSocket соединение для пользователя и обрабатывает события
        через WebSocket.
      produces:
      - application/json
      responses:
        "101":
          description: WebSocket соединение успешно установлено
          schema:
            type: string
        "400":
          description: Ошибка при установке WebSocket соединения
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Подключение к WebSocket
      tags:
      - WebSocket
swagger: "2.0"
